<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Unni-PC" ignored="0" name="Test" tests="7" failures="3" timestamp="28 Jan 2022 14:44:32 GMT" time="247.787" errors="0">
  <testcase name="loginTest" time="3.985" classname="com.akBanking.testCases.TC_Logintest_001"/>
  <testcase name="loginDDT" time="11.958" classname="com.akBanking.testCases.TC_LogintestDP_002"/>
  <testcase name="loginDDT" time="12.124" classname="com.akBanking.testCases.TC_LogintestDP_002"/>
  <testcase name="loginDDT" time="6.3" classname="com.akBanking.testCases.TC_LogintestDP_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.akBanking.testCases.TC_LogintestDP_002.loginDDT(TC_LogintestDP_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="6.258" classname="com.akBanking.testCases.TC_LogintestDP_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.akBanking.testCases.TC_LogintestDP_002.loginDDT(TC_LogintestDP_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="5.603" classname="com.akBanking.testCases.TC_LogintestDP_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.akBanking.testCases.TC_LogintestDP_002.loginDDT(TC_LogintestDP_002.java:35)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="addNewCustomer" time="22.504" classname="com.akBanking.testCases.TC_AddCustomertest_003"/>
</testsuite> <!-- Test -->
